# Generated by Django 5.1.7 on 2025-03-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserKeys',
            new_name='KeyPair',
        ),
    ]
