# Generated by Django 5.1.7 on 2025-03-23 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_userkeys_keypair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keypair',
            name='private_key',
        ),
    ]
